### ISSUE TITLE
Storativity Task List

### ISSUE THREAD

**Issue by jamiebyer** [jamiebyer/EOSC325#1]
- [x] Adjust Porosity: Select "min, middle, max" of range, using values for each material as per Table 1 (pg 11) in hydrology book
- [x] Can't find porosity values for Jointed and Sound rocks.
- [x] Water density: select from 3 options: find values for potable, sea water, and brine (deep aquifers can be very saline)
- [x] Table for radiobutton values
- [x] Vertical water density with values
- [x] Add units everywhere

**Comment by fhmjones** [comment]
First thoughts: 
- I believe this will end up as a demonstration rather than an assignment. 
- selectable choice of units is probably lower priority, but units need to be clearly identified.
- I think topography was just an idea - I'm not sure it even makes a difference, but it is a line on the original spreadsheet
- "Constraints on parameters" means restrict values to be reasonable physically. This depends on units. Best step is duplicate the values used in the spreadsheet first.

**Comment by fhmjones** [comment]
Based on viewing July 27 (Looking good!): 
- Maybe "L" isn't needed. 
- In "notes" lets add a few lines identifying typical ranges in your units for materials - based on figure 32 in the [hydrogeologic properties](https://gw-project.org/books/hydrogeologic-properties-of-earth-materials-and-principles-of-groundwater-flow/) book.
-

**Comment by fhmjones** [comment]
- Topography should be fixed. Then, when watertable is above (eg with high recharge), it shows ground can no longer absorb available water - this becomes a "flooding" event. 
- we'll want to restrict values to reasonable. h1 and h2 based partly on fixed topography; recharge to reasonable rainfall and evaporation rates, K to be logarithmic for one type of material only - e.g. "silty sand". 
- fix the q_x axis, so the line changes "shape" when flow rates change in the model. 
- others likely after talking with Ali
