### ISSUE TITLE
Unconfined Flow Task List

### ISSUE THREAD

**Issue by fhmjones** [jamiebyer/EOSC325#4]
From call with Ali:
- [x] Change title from "EOSC 325: Unconfined Flow with Recharge" to "Unconfined 'linear' flow with recharge"
- [x] Remove text in instructions: (Ver: Aug 19, 2021).
Old:
- [x] Note the value of K in a graph annotation, maybe bottom right in the aquifer. 
- [x] Maybe in slider title too? 
- [x] Introduction might look nicer if the figure is resized to a little smaller, then placed to the right of the introduction text. 
- [ ] Also, the source of this figure should be noted if it's not substantially different from the original. Attribution could be small text in the figure itself. These are minor points - but "looking nice" is worth while if we have time and it's easy - and attribution is always important. 
- [x] logarithmic K: Use [this](https://dash.plotly.com/dash-core-components/slider) to make logarithmic sliders. 
- [ ] Can the equation for head as a function of x (distance between h1 and h2) be included in the introduction? I have a feeling that math can't be rendered easily using the dcc.markdown approach. Maybe as a figure?

**Comment by jamiebyer** [comment]
logarithmic K: I can convert the value of the slider as suggested, but the little display with the current slider value would be incorrect, and I don't think there's a way to change that.

**Comment by fhmjones** [comment]
How about this trick? https://dash.plotly.com/dash-core-components/slider
