### ISSUE TITLE
Thiem Task List

### ISSUE THREAD

**Issue by jamiebyer** [jamiebyer/EOSC325#5]
- [x] Tick marks
- [x] Graph interactivity
- [x] Values on sliders
- [x] Combine with F-D

**Comment by fhmjones** [comment]
- [x] Scale back so it looks like https://github.com/fhmjones/hydro-thiem . Ali really only wants it to "answer" one question. That is: "what will the drawdown curve look like for various outflow or transmissivity values?" If he wants this app to answer other questions, we'll incorporate them later. 
- NOTE my code is probably awkward and its may be more efficient to get there with your own adjustments. Maybe even start a new "app.py". 

- [ ] Low priority: Might be nice to put the graph on a figure, but aligning the pieces of the figure with the plotted curve might get finicky. 

- [ ] new task: lets continue to use md file for introductory information. Which raises the next question or task:

- [x] new task: (lower priority) can we get a figure into the "introductory" text? This would be nice, but "smaller".

![drawdown-sketch](https://user-images.githubusercontent.com/16675713/130294573-4b3721ca-a930-47dd-bbb7-c442ff85dc29.png)
